version: '3.7'
services:
  testproject:
    build: .
    command: gunicorn testproject.wsgi
    volumes:
      - ./app/:/usr/src/testproject/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=itfox
      - POSTGRES_PASSWORD=passW0rd
      - POSTGRES_DB=itfox-test
volumes:
  postgres_data: